language: python
python:
    - "3.7"
    #- "3.8-dev"

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - pytest

notifications:
    slack: w1566050171-ore544597:qrufrcYdFo2qxomjGYMJ1Xol
        on_success: always
        on_failure: always
